### ISSUE TITLE
Attempted to load class for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Tander** [MeinKraft/CrimsonNBTTags#1]
Mod crashes server. Would be nice to see a fix

crashlog:
https://paste.gg/p/anonymous/b271d688141c41aeb1cd5769864c6a0f

**Comment by MeinKraft** [comment]
if my server ever comes back online, i'll test it

I assume it works in singleplayer? as its reporting a server side error

**Comment by Tander** [comment]
Yep, it works now. And finally shows that all mods matched. 
![изображение](https://user-images.githubusercontent.com/1059805/123504033-777f4a00-d65f-11eb-9663-d64746e93266.png)

Neat. Waiting for upload on curseforge then.

**Comment by MeinKraft** [comment]
uploaded fix, waiting on CurseForge to approve

Thank you
